{{
	Form::select($name, [
		''=>'Selecione uma região...',
		'Águas Claras'=>'Águas Claras',
		'Asa Norte'=>'Asa Norte',
		'Asa Sul'=>'Asa Sul',
		'Brazlândia'=>'Brazlândia',
		'Candangolândia'=>'Candangolândia',
		'Ceilândia'=>'Ceilândia',
		'Cruzeiro'=>'Cruzeiro',
		'Estrutural'=>'Estrutural',
		'Fercal'=>'Fercal',
		'Gama'=>'Gama',
		'Granja do Torto'=>'Granja do Torto',
		'Guará'=>'Guará',
		'Itapoã'=>'Itapoã',
		'Jardim Botânico'=>'Jardim Botânico',
		'Lago Norte'=>'Lago Norte',
		'Lago Sul'=>'Lago Sul',
		'Noroeste'=>'Noroeste',
		'Núcleo Bandeirante'=>'Núcleo Bandeirante',
		'Octogonal'=>'Octogonal',
		'Paranoá'=>'Paranoá',
		'Park Sul'=>'Park Sul',
		'Park Way'=>'Park Way',
		'Planaltina'=>'Planaltina',
		'Plano Piloto'=>'Plano Piloto',
		'Recanto das Emas'=>'Recanto das Emas',
		'Riacho Fundo'=>'Riacho Fundo',
		'Samambaia'=>'Samambaia',
		'Santa Maria'=>'Santa Maria',
		'São Sebastião'=>'São Sebastião',
		'SIA'=>'SIA',
		'Sobradinho'=>'Sobradinho',
		'Sudoeste'=>'Sudoeste',
		'Taguatinga'=>'Taguatinga',
		'Varjão'=>'Varjão',
		'Vicente Pires'=>'Vicente Pires',
		'Vila Planalto'=>'Vila Planalto'
	]
	, $selected , $attr)
}}
